"""create users table

Revision ID: c72c6d99f0c1
Revises: 
Create Date: 2026-07-24 17:16:10.312996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72c6d99f0c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Student', 'Teacher', name='role'), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('matriculation', sa.String(), nullable=True),
    sa.Column('handle_sheet', sa.String(), nullable=True),
    sa.Column('handle_observed', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('gmail', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('codeforces', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('citizenship', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status_line', sa.String(), nullable=True),
    sa.Column('primary_cohort', sa.String(), nullable=True),
    sa.Column('past_cohorts', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.JSON(), nullable=False),
    sa.Column('link_nonce', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriculation'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_primary_cohort'), 'users', ['primary_cohort'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_primary_cohort'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
